config/routes.rb
ReEducation::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  match 'login' => 'sessions#new', :as => 'login', :via => :get
  match 'logout' => 'sessions#destroy', :as => 'logout', :via => :get
  match 'about-us' => 'site#about', :as => 'about_us', :via => :get
  match 'sitemap.xml' => 'site#sitemap'

  resources :sessions, :only => [:create]

  resources :lessonplans do
    resources :tasks, :only => [:index, :create]
    resources :comments, :only => [:index, :create, :destroy]
    resources :lessonplan_attachments, :as => 'attachments', :path => 'attachments', :only => [:index, :create, :destroy] do
      resources :comments, :only => [:index, :show, :create, :destroy]
    end
  end

  resources :publishers, :except => [:index]
  resources :users
  resources :feedbacks, :only => [:new, :create]
  resources :uploads

  root :to => 'lessonplans#index'

end

app/models/lessonplan.rb
# == Schema Information
#
# Table name: lessonplans
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  content           :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  short_description :string(255)
#  symbol_img_url    :string(255)
#  attachment        :string(255)
#  user_id           :integer
#  publisher_id      :integer
#

class Lessonplan < ActiveRecord::Base
  has_many :tasks, :dependent => :delete_all
  has_many :comments, :as => :commentable, :dependent => :delete_all
  has_many :lessonplan_attachments, :dependent => :delete_all

  belongs_to :publisher

  mount_uploader :attachment, AttachmentUploader

  def images
    attachments(%w[jpg jpeg gif png bmp])
  end

  def scratches
    attachments(%w[sb])
  end

  def symbol_image
    return self.symbol_img_url if self.symbol_img_url.present?
    self.attachment.thumb.url
  end

  def attachments(extensions)
    ret = []
    self.lessonplan_attachments.order('created_at DESC').each do |attachment|
      ret.push attachment if attachment.name && extensions.include?(attachment.name.split('.').last.downcase)
    end
    ret
  end

  def has_image_attachments?
    images.length > 0
  end

  def has_sctrach_attachments?
    scratches.length > 0
  end

  def attachment_filename
    read_attribute(:attachment)
  end

  def self.list_last num
    self.limit(num).order('created_at DESC')
  end

  def create_tasks(tasks)
    self.tasks.destroy_all
    tasks.each { |task| self.tasks.create! task } if tasks.present?
  end

  def self.ordered_lessonplans
    title_filters = ReEducation::Application.config.lessonplan_title_filters.reverse
    ordered_lessonplans = Lessonplan.all.reverse

    title_filters.each do |title|
      lessonplan = ordered_lessonplans.select{ |l| l.title == title }.first
      ordered_lessonplans.prepend(ordered_lessonplans.delete(lessonplan)) unless lessonplan.nil?
    end
    ordered_lessonplans
  end

end

app/controllers/lessonplans_controller.rb
class LessonplansController < ApplicationController

  load_and_authorize_resource

  def index
    @lessonplans = Lessonplan.list_last 4
  end

  def create
    lessonplan = current_user.lessonplans.create(lessonplan_params)
    lessonplan.create_tasks(tasks_params) if lessonplan

    redirect_to lessonplan_path(lessonplan)
  end


  def update
    lessonplan = Lessonplan.find(params[:id])
    lessonplan.update_attributes(lessonplan_params)
    lessonplan.create_tasks(tasks_params)

    redirect_to lessonplan_path(lessonplan)
  end

  def destroy
    lessonplan = Lessonplan.find(params[:id])
    lessonplan.destroy

    redirect_to root_url
  end

  def lessonplan_params
    params[:lessonplan].slice(:title, :content, :short_description, :symbol_img_url, :attachment)
  end

  def tasks_params
    tasks = []
    if params[:tasks].present?
      params[:tasks].each do |task|
        tasks << task.slice(:title, :content)
      end
    end
    tasks
  end

end

app/helpers/lessonplans_helper.rb
module LessonplansHelper
end

app/views/lessonplans/edit.html.haml
.container.content
  %nav.breadcrumb
    %ul
      %li
        %a{ :href => "javascript:;" } 首页
      %li
        %a{ :href => "javascript:;" } 案例
      %li.active
        %a{ :href => "javascript:;" } 精品
      
%article.plan.edit
  = form_for @lessonplan, :url => { :action => 'update' } do |f|

    %section.title-section
      %h3 教案名称
      = f.text_field :title, :placeholder => '给你的教案起一个名字...', class: "large"
      
    %section
      %h3 教案介绍
      .multi-column-section
        .preview-uploader-wrapper{ 'ng-controller' => 'PreviewController', 'ng-init' => "init(\"#{@lessonplan.symbol_image}\");" }
          %a.reset-btn{ 'ng-click' => 'reset();', 'ng-show' => 'previewImageUrl' } &times;
          %span.uploder-placeholder
            %a{ href: "javascript:;" } 设置封面
            %input.jquery-file-uploader{ type: "file", name: "file", :accept => "image/*" }
          %img{ 'ng-src' => "{{previewImageUrl}}", 'ng-show' => "previewImageUrl" }
          = f.text_field :symbol_img_url, 'ng-model' => 'previewImageUrl', class: 'hide'

        .description-wrapper
          = label_tag 'lessonplan[short_description]', '说出这个教案的亮点(140字)'
          = f.text_area :short_description, :rows => 4, :maxlength => 140, :cols => 60

    %section
      %h3.clearfix 详细内容
      %label 简要说明年级、学科、学生情况、可能的困难等...
      = description_editor f

    %section.plan-step
      %h3 活动步骤
      = render :partial => "shared/lessonplan_editable_tasks", locals: { lessonplan: @lessonplan }
    %section.user-operation
      = f.submit '保存教案', :class => 'btn btn-primary'
      %a{ :href => "#{lessonplan_path(@lessonplan.id)}" } 放弃修改

app/views/lessonplans/index.html.erb
<article class="main">
  <h1>新的课堂，你来设计</h1>
  <small class="slogan">新的课堂是设计和实践体验式教学的平台</small>
  <p>
    <a class="btn btn-primary" href="<%= new_lessonplan_path() %>">创建教案</a>
  </p>
  <section class="description">
    <ul class="description">
      <li class="age">
        <b>体验式教学</b>
        <small>面向小学4年级到初中2年级的各学科</small>
      </li>
      <li class="design">
        <b>汇聚教学案例</b>
        <small><%= Lessonplan.all.length %>门充满互动和创意的体验式课程</small>
      </li>
      <li class="classroom">
        <b>各地老师互动协作</b>
        <small>和全国200位富有创造力的老师协作和学习</small>
      </li>
      <li class="feedback">
        <b>分享授课成果</b>
        <small>看看各地孩子有什么不同作品</small>
      </li>
    </ul>
  </section>
  <section class="example">
    <h3>我们的课</h3>
    <ul>
      <% Lessonplan.ordered_lessonplans.each do |lessonplan| %>
        <li>
          <a href="<%= lessonplan_path(lessonplan.id) %>"><b class="title"><%= lessonplan.title %></b></a>
          <p class="description"><%= lessonplan.short_description.html_safe %></p>
          <a href="<%= lessonplan_path(lessonplan.id) %>" class="enter">进入</a>
        </li>
      <% end %>
    </ul>
  </section>
</article>
    

app/views/lessonplans/index.html.haml
/ .course-header.home.clearfix
/   %h1 家乡
.page.container
  .new-plan.section.clearfix
    #myCarousel.container.carousel.slide{ 'data-interval' => '10000', 'data-pause' => 'hover'}
      .carousel-inner
        .active.item
          .pull-left

            %h1 让孩子获得更有意思的课程
            %p 为“我的家乡”这个主题建立一个有意思的课程计划。
            %p 
              %button.btn.btn-new-plan{ :onclick => "window.location.href='/lessonplans/new'" , :type => "button" }
                新的课程计划 
                %i.icon-plus-sign.icon-white
            
          %img.pull-right.hero{ :src => "assets/hero1.png" }
        .item
          .pull-left

            %h1 提出一个教学想法
            %p 比如通过探访家乡的小吃了解家乡
            
          %img.pull-right.hero{ :src => "assets/i-have-idea.png" }

        .item
          .pull-left

            %h1 添加一些教学条目
            %p 比如拍摄一张你最喜欢的小吃照片或者画一张美食地图
            
          %img.pull-right.hero{ :src => "assets/add-tasks.png" }

        .item
          .pull-left

            %h1 收集全国各地老师的建议
            %p 你还可以从其他专业的老师获得其他的知识补充
            
          %img.pull-right.hero{ :src => "assets/class-everywhere.png" }

        .item
          .pull-left

            %h1 用这个教案上一堂生动的体验课吧
            %p 按照教案的过程和学生一起利用体验教学的方式走出教室
            
          %img.pull-right.hero{ :src => "assets/activities.png" }

        .item
          .pull-left

            %h1 上传完成的作业和大家一起分享
            %p 看看其他城市甚至其他国家的学生是如何完成这个课程的
            
          %img.pull-right.hero{ :src => "assets/homework.png" }

        .item
          .pull-left

            %h1 我们来自新的课堂
            %p 一个致力于将体验式教学理念传播到更多中小学教学中的组织
            
          %img.pull-right.hero{ :src => "assets/welcome-open-class.png" }

      %a.carousel-control.left{ :href => "#myCarousel", "data-slide" => "prev" } ‹
      %a.carousel-control.right{ :href => "#myCarousel", "data-slide" => "next" } ›
  .home.main.container-fluid.clearfix
    .row-fluid
      .span5
        .section
          %h3 特别推荐
          %ul.feature-list
            
      .span3
        .section
          %h3 最新课程
          %ul.plan-list
            - @lessonplans.each_index do |idx|
              %li.row-fluid.clearfix
                .span3
                  %img.plan-avatar{ :src => @lessonplans[idx].symbol_img_url }
                .plan-intro.span9
                  %h5 
                    =link_to @lessonplans[idx].title, "/lessonplans/#{@lessonplans[idx].id}"
                  %p
                    = @lessonplans[idx].short_description

     
      .span4
        .section
          %h3 正在发生
          %ul.event-list

  %hr.soften
  .ongoing-plan.row.clearfix

app/views/lessonplans/new.html.haml
.container.content
  %nav.breadcrumb
    %ul
      %li
        %a{ :href => "#" } 首页
      %li
        %a{ :href => "#" } 案例
      %li.active
        %a{ :href => "#" } 精品

%article.plan.edit
  = form_for :lessonplan, :url => { :action => 'create' } do |f|

    %section.title-section
      %h3 教案名称
      = f.text_field :title, :placeholder => '给你的教案起一个名字...', class: "large"

    %section
      %h3 教案介绍

      .multi-column-section
        .preview-uploader-wrapper{ 'ng-controller' => 'PreviewController', 'on-load' => 'init();' }
          %a.reset-btn{ 'ng-click' => 'reset();', 'ng-show' => 'previewImageUrl' } &times;
          %span.uploder-placeholder
            %a{ href: "javascript:;" } 设置封面
            %input.jquery-file-uploader{ type: "file", name: "file", :accept => "image/*" }
          %img{ 'ng-src' => "{{previewImageUrl}}", 'ng-show' => "previewImageUrl" }
          = f.text_field :symbol_img_url, 'ng-model' => 'previewImageUrl', class: 'hide'

        .description-wrapper
          = label_tag 'lessonplan[short_description]', '说出这个教案的亮点(140字)'
          = f.text_area :short_description, :rows => 4, :maxlength => 140, :cols => 60

    %section
      %h3.clearfix 详细内容
      %label 简要说明年级、学科、学生情况、可能的困难等...
      = description_editor f

    %section.plan-step
      %h3 活动步骤
      = render :partial => "shared/lessonplan_editable_tasks", locals: { lessonplan: nil }
    %section.user-operation
      = f.submit '保存教案', :class => 'btn btn-primary'

app/views/lessonplans/show.html.haml
#{ @title = @lessonplan.title }
%nav.breadcrumb
  %ul
    %li
      %a{ :href => "javascript:;" } 首页
    %li
      %a{ :href => "javascript:;" } 案例
    %li.active
      %a{ :href => "javascript:;" } 精品

%article.plan{ 'ng-controller' => "PlanController" }
  -if can? :update, @lessonplan or can? :destroy, @lessonplan
    %p.page-action
      -if can? :update, @lessonplan
        %a.btn.btn-info.plan-action{ :href => "#{edit_lessonplan_path(@lessonplan.id)}"} 编辑
      -if can? :destroy, @lessonplan
        = link_to '删除', lessonplan_path(), :confirm => '确定要删除么？', :method => :delete, :class => 'btn btn-danger', :id => 'delete_button'

  %h2= @lessonplan.title

  = render :partial => "shared/lessonplan_items", :locals => { :lessonplan => @lessonplan }

  %section.activity
    %img.main{ :src => @lessonplan.symbol_image, :alt => @lessonplan.title }
    %p.description= @lessonplan.short_description.html_safe
    %h3 活动介绍
    = @lessonplan.content.html_safe

    - unless @lessonplan.tasks.empty?
      %section.plan-step.clearfix{'ng-controller' => 'TasksController', 'ng-init' => "init(#{@lessonplan.id})"}
        %h3 活动步骤 [{{tasks.length}}]
        %ol.steps
          %li{ 'ng-repeat' => 'task in tasks', :class => "{{getItemCssClass($index)}}" }
            %label {{$index + 1}}
            %div
              %b {{task.title}}
              %div{ 'ng-bind-html-unsafe' => 'task.content' }

  = render :partial => "shared/publisher_aside", :locals => { :publisher => @lessonplan.publisher }

  %section#comments.comments{ 'ng-controller' => 'CommentsController', 'ng-init' => "init(#{@lessonplan.id})" }
    %h3 评论[{{comments.length}}]
    %ul
      %li.comment.clearfix{ 'ng-repeat' => 'comment in comments' }
        .comment-avatar
          %img{ 'ng-src' => "{{getAvatar(comment.publisher)}}" }
        .comment-content
          %a.nick-name{ :href => "{{getUrl(comment.publisher)}}" } {{comment.publisher.alternative_name}}
          %time.comment-time {{formatDateTime(comment.updated_at)}}
          -if super_manager?
            %a.delete{:href=>"javascript:;", 'ng-click' => 'remove($index)'} 删除
          -else
            :erb
              <ng-switch on="comment.publisher_id">
                <a class="delete" ng-switch-when="<%= current_user.id unless current_user.nil? %>" href="javascript:;" ng-click="remove($index)">删除</a>
              </ng-switch>

          %p {{comment.content}}
      - if online?
        .comment.clearfix
          = form_for :comment, :url => lessonplan_comments_url(@lessonplan), :html => { 'ng-submit' => 'submitForm()' } do |f|
            = f.text_area :content, :placeholder => "评论一下这个教案...", :rows => 5, 'ng-model' => 'new_comment_content'
            = f.submit '评论', :class => 'btn btn-primary'

  
            