config/routes.rb
ReEducation::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  match 'login' => 'sessions#new', :as => 'login', :via => :get
  match 'logout' => 'sessions#destroy', :as => 'logout', :via => :get
  match 'about-us' => 'site#about', :as => 'about_us', :via => :get
  match 'sitemap.xml' => 'site#sitemap'

  resources :sessions, :only => [:create]

  resources :lessonplans do
    resources :tasks, :only => [:index, :create]
    resources :comments, :only => [:index, :create, :destroy]
    resources :lessonplan_attachments, :as => 'attachments', :path => 'attachments', :only => [:index, :create, :destroy] do
      resources :comments, :only => [:index, :show, :create, :destroy]
    end
  end

  resources :publishers, :except => [:index]
  resources :users
  resources :feedbacks, :only => [:new, :create]
  resources :uploads

  root :to => 'lessonplans#index'

end

app/views/shared/_embed_scratch.html.erb
<% unless source_url.nil? then %>
    <object width="100%" height="100%" type="application/x-shockwave-flash" data="/tools/Scratch.swf">
      <!-- <object width="100%" height="100%" type="application/x-shockwave-flash" data="http://scratch.mit.edu/static/misc/PlayerOnly.swf"> -->
      <param name="allowScriptAccess" value="always">
      <param name="allowFullScreen" value="true">
      <param name="flashvars" value="project=<%= root_url + source_url %>?version=2">
    </object>
<% end %>

app/views/shared/_footer.html.haml
/ %footer.footer
/   %small Powered by ThoughtWorks Inc. China

app/views/shared/_header.html.erb
<header>
  <nav>
    <h1><a href="/">新的课堂</a></h1>
    <ul>
      <% unless online? %>
        <li>
          <a href="<%= new_publisher_path() %>">注册</a>
        </li>
        <li>
          <a href="<%= login_path() %>">登录</a>
        </li>
      <% else %>
        <li>
          <a href="<%= new_lessonplan_path() %>">创建新教案</a>
        </li>
        <li>
          <a href="<%= publisher_path current_user %>">我的信息</a>
        </li>
        <li>
          <a href="<%= logout_path() %>">退出</a>
        </li>
      <% end %>
        <li>
          <a class="icon-email feedback" href="mailto:newclass.org@gmail.com">提供建议</a>
        </li>
        <li>
          <form target="_blank" class="search-container" action="http://www.baidu.com/baidu" method="GET">
            <input name="word" type="text" class="search" placeholder="搜索教案">
            <input name="tn" type="hidden" value="bds">
            <input name="cl" type="hidden" value="3">
            <input name="ct" type="hidden" value="2097152">
            <input name="si" type="hidden" value="www.newclass.org">
            <input type="submit" class="do-search" value="搜索">
          </form>
        </li>
    </ul>
  </nav>
</header>

app/views/shared/_lessonplan_editable_tasks.html.haml
- init_arg = lessonplan.present? ? lessonplan.id : ''
%ol.steps{ 'ng-controller' => 'CachedTasksController', 'ng-init' => "init(#{init_arg});" }
  %li{ 'ng-repeat' => 'task in cachedTasks', :class => 'editable-task-item-{{$index}}', 'ng-controller' => 'TaskController' }
    %label {{$index + 1}}
    .step-content
      %div
        %label 步骤名称
        %input.task-item-title.focus-editable{ :placeholder => '填写一个教学活动步骤...', "ng-model" => 'task.title', :type => 'text', :name => 'tasks[][title]' }
        %label
          详细内容
        .wysihtml5-wrapper
          .toolbar{ :style => "display: none;" }
            %a{ 'data-wysihtml5-command' => "bold", :title => "加粗" } &#xe77a;
            %a{ 'data-wysihtml5-command' => "insertUnorderedList", :title => "无序列表" } &#xf0ca;
            %a{ 'data-wysihtml5-command' => "insertOrderedList", :title => "有序列表" } &#xf0cb;
            %a.file-upload-wrapper{  href: 'javascript:;', title: "添加图片" }
              &#x1f304;
              %input.jquery-file-uploader{ type: "file", name: "file", multiple: "true", :accept => "image/*" }
            %span.upload-progress-status{ 'ng-show' => 'showUploadProgress' } 正在上传 {{uploadProgress}}%
          %textarea.wysihtml5.task-item-content.focus-editable{ :placeholder => '每一步如何做，才能完成这堂课...', :maxlength => 1000, "ng-model" => 'task.content', :value => '{{task.content}}', :name => 'tasks[][content]' }
        %input{ :type => 'hidden', :value => '{{task.id}}', :name => 'tasks[][id]' }
      %a.btn.btn-danger.delete.plan-action{ :href => 'javascript:;', 'ng-click' => 'deleteTask($index)', :title => '删除' } 删除
  %li.new-step
    %a.btn{ :href => 'javascript:;', 'ng-click' => 'addTask()' } 添加步骤

app/views/shared/_lessonplan_items.html.haml
- active = :content if active.nil?
- unless lessonplan.nil?
  %ul.plan-menu
    %li{ :class => "#{"current" if active == :content}" }
      %a{ :href => lessonplan_path(lessonplan) } 内容
    - if lessonplan.title == "造纸桥"
      %li{ :class => "#{"current" if active == :ppt}" }
        %a{ :href => "/ppt.html?#{lessonplan.id}" }
          幻灯片
    %li{ :class => "#{"current" if active == :comments}" }
      %a{ :href => lessonplan_path(lessonplan) + "#comments" }
        讨论
        %label{ 'ng-init' => 'commentsCount=' + lessonplan.comments.length.to_s }
          {{commentsCount}}

    %li{ :class => "#{"current" if active == :attachments}" }
      %a{ :href => lessonplan_attachments_path(lessonplan) }
        作业
        %label{ 'ng-init' => 'attachmentsCount=' + lessonplan.lessonplan_attachments.length.to_s }
          {{attachmentsCount}}

app/views/shared/_lessonplan_teaser_list.html.haml
%ul.teaser-list
  - lessonplans.reverse.each do |lessonplan|
    %li 
      %h4 
        %a{ :href => "#{lessonplan_path(lessonplan)}"}= lessonplan.title
      %p= lessonplan.short_description
      %a.enter{ :href => "#{lessonplan_path(lessonplan)}" } 进入

app/views/shared/_publisher_aside.html.haml
- if publisher.present?
  %aside.author
    %b.title 课程设计者
    %img.avatar{ :src => publisher.avatar_link }
    %a.name{ :href => publisher_path(publisher) }
      = publisher.name
    %p= publisher.short_description