config/routes.rb
ReEducation::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  match 'login' => 'sessions#new', :as => 'login', :via => :get
  match 'logout' => 'sessions#destroy', :as => 'logout', :via => :get
  match 'about-us' => 'site#about', :as => 'about_us', :via => :get
  match 'sitemap.xml' => 'site#sitemap'

  resources :sessions, :only => [:create]

  resources :lessonplans do
    resources :tasks, :only => [:index, :create]
    resources :comments, :only => [:index, :create, :destroy]
    resources :lessonplan_attachments, :as => 'attachments', :path => 'attachments', :only => [:index, :create, :destroy] do
      resources :comments, :only => [:index, :show, :create, :destroy]
    end
  end

  resources :publishers, :except => [:index]
  resources :users
  resources :feedbacks, :only => [:new, :create]
  resources :uploads

  root :to => 'lessonplans#index'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  # if email must presence, why email format validate allow_blank is true ??

  validates :email, :body, :presence => true
  validates :email, :format => { :with => /^[a-z0-9+\-_\.]+@[a-z0-9\-_\.]+\.[a-z]{2,}$/i }, :allow_blank => true

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      NotificationsMailer.new_feedback(@feedback).deliver
    else
      flash.now[:alert] = 'Please fill all fields.'
      render :new
    end
  end

  private

  def feedback_params
    params[:feedback].slice(:email, :body)
  end

end

app/views/feedbacks/create.html.haml
.page.container.contact-us-body.thanks
  %div.col-img
    %img{:src=> '/assets/contact-us-img.png'}
  %div.col-text
    %h2 谢谢您的建议。
    %p 感谢您的想法与建议，我们会及时与您联系。
    %hr
    %div.home-button
      %a{:href => '/'}      
        %img{:src=> '/assets/home-button.png'}
    
    

app/views/feedbacks/new.html.haml
.page.container.contact-us-body
  %div.col-img
    %img{:src=> image_path('contact-us-img.png')}
  %div.col-text
    %h2 我有一些建议。
    %p 请不要犹豫，我们需要您的意见，并帮助我们不断的改进！
    %hr
    = form_for @feedback, :url => feedbacks_path do |form|
      %fieldset.fields
        .field
          .field
            = label_tag '@feedback[email]', '您的邮箱地址是？'
            = form.text_field :email, :placeholder => '例如: xiong.mao@hotmail.com'

          .field
            = label_tag '@feedback[body]', '您的想法与建议是？'
            = form.text_area :body, :placeholder => '最好200个字以内哦～', :rows => 4, :maxlength => 200
      %fieldset.actions
        = form.submit "提交反馈", :class => 'btn btn-contact-us'