config/routes.rb
ReEducation::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  match 'login' => 'sessions#new', :as => 'login', :via => :get
  match 'logout' => 'sessions#destroy', :as => 'logout', :via => :get
  match 'about-us' => 'site#about', :as => 'about_us', :via => :get
  match 'sitemap.xml' => 'site#sitemap'

  resources :sessions, :only => [:create]

  resources :lessonplans do
    resources :tasks, :only => [:index, :create]
    resources :comments, :only => [:index, :create, :destroy]
    resources :lessonplan_attachments, :as => 'attachments', :path => 'attachments', :only => [:index, :create, :destroy] do
      resources :comments, :only => [:index, :show, :create, :destroy]
    end
  end

  resources :publishers, :except => [:index]
  resources :users
  resources :feedbacks, :only => [:new, :create]
  resources :uploads

  root :to => 'lessonplans#index'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def sitemap
    #headers['Content-Type'] = 'application/xml'
    @lessonplans = Lessonplan.all
    @last_modify = Lessonplan.order('updated_at').last.updated_at

    render :layout => false, :formats => :xml
  end

end

app/views/site/about.html.erb
<article id="about-us" class="main">
  <h1>我们是新的课堂</h1>
  <small class="slogan">我们来自教育大发现，致力于推广中国中小学的体验式教学</small>
  <section class="short-description">
    <h2>我们提供</h2>
    <ul>
      <li>
        <img src="/assets/gather.fw.png" alt="教案丰富">
        <b>教案丰富</b>
        <small>百个中小学体验式教学案例</small>
      </li>
      <li>
        <img src="/assets/work.fw.png" alt="互动协作">
        <b>互动协作</b>
        <small>基于教案进行讨论和互动</small>
      </li>
      <li>
        <img src="/assets/share.fw.png" alt="成功分享">
        <b>成果分享</b>
        <small>展示孩子们的作品</small>
      </li>
    </ul>
  </section>
  <section class="team-description">
    <h2>我们的团队</h2>
    <p>我们的团队由热心中国教育的15名公益人组成，有长期从事中小学教育的实践者、体验式教育的研究者、互联网产品的产品经理、交互设计师、以及程序员，这个平台有我们共同的心血，我们来自教育大发现社区、ThoughtWorks中国、超有爱科技、彩程设计、Ruby社区。</p>
    <p>期待更多人加入我们，一起为中国中小学教育加油。</p>
    <img src="/assets/team.fw.png" alt="团队成员">
  </section>
  <section class="contact-us">
    <h2>联系我们</h2>
    <ul>
      <li class="email"><a href="mailto:newclass.org@gmail.com">newclass.org@gmail.com</a></li>
      <li class="weibo"><a href="http://weibo.com/learnbeta">@新的课堂</a></li>
      <li class="address"><a href="http://j.map.baidu.com/FruIh">成都天府软件园E区E1栋705</a></li>
    </ul>
  </section>
  <section class="partner">
    <h2>合作伙伴</h2>
    <ul>
      <li><a href="http://www.sociallearnlab.org/ "><img src="/assets/partner-sociallearnlab.png" alt="教育大发现"></a></li>
      <li><a href="http://www.thoughtworks.com/"><img src="/assets/partner-thoughtworks.png" alt="ThoughtWorks"></a></li>
      <li><a href="http://mycolorway.com"><img src="/assets/partner-mycolorway.png" alt="彩程设计"></a></li>
      <li><a href="http://www.baicizhan.com"><img src="/assets/partner-chaoyouai.png" alt="百词斩"></a></li>
      <li><a href="http://qiniutek.com/"><img src="/assets/qiniu.png" alt="七牛科技"></a></li>
      <li><a href="http://pragmatic.ly/"><img src="/assets/pragmaticly.png" alt="pragmatic.ly"></a></li>
    </ul>
  </section>

</article>
    

app/views/site/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>http://www.newclass.org/</loc>
    <lastmod><%= @last_modify %></lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.00</priority>
  </url>

  <url>
    <loc>http://www.newclass.org/about-us</loc>
    <lastmod><%= @last_modify %></lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.50</priority>
  </url>

<% Lessonplan.ordered_lessonplans.each do |lessonplan| %>
  <url>
    <loc>http://www.newclass.org<%= lessonplan_path(lessonplan.id) %></loc>
    <lastmod><%= lessonplan.updated_at %></lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.80</priority>
  </url>
<% end %>

</urlset>